import 'package:flutter_travel_audio_guide/features/activity/domain/entities/activity.dart';

Activity buildTestActivity({
  int id = 1,
  String title = '台北燈節',
  String description = '<p>活動介紹內容</p>',
  String begin = '2026-08-01',
  String end = '2026-08-10',
  String posted = '2026-07-01',
  String modified = '2026-07-25',
  String url = '',
  String address = '台北市中正區',
  String distric = '中正區',
  String nlat = '25.03',
  String elong = '121.56',
  String organizer = '臺北市政府',
  String coRganizer = '',
  String contact = '',
  String tel = '',
  String ticket = '',
  String traffic = '',
  String parking = '',
  List<ActivityLink> links = const [],
}) {
  return Activity(
    id: id,
    title: title,
    description: description,
    begin: begin,
    end: end,
    posted: posted,
    modified: modified,
    url: url,
    address: address,
    distric: distric,
    nlat: nlat,
    elong: elong,
    organizer: organizer,
    coRganizer: coRganizer,
    contact: contact,
    tel: tel,
    ticket: ticket,
    traffic: traffic,
    parking: parking,
    links: links,
  );
}
